/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'tacticalDrills' : IDL.Null,
  'victoryZone' : IDL.Null,
  'missionCritical' : IDL.Null,
  'scouting' : IDL.Null,
});
export const SyllabusItem = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'tasks' : IDL.Vec(IDL.Text),
  'topic' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'chapter' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTaskToSyllabusItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createSyllabusItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllSyllabusItems' : IDL.Func([], [IDL.Vec(SyllabusItem)], ['query']),
  'getSyllabusItem' : IDL.Func([IDL.Text], [SyllabusItem], ['query']),
  'updateTaskStatus' : IDL.Func([IDL.Text, IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'tacticalDrills' : IDL.Null,
    'victoryZone' : IDL.Null,
    'missionCritical' : IDL.Null,
    'scouting' : IDL.Null,
  });
  const SyllabusItem = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'tasks' : IDL.Vec(IDL.Text),
    'topic' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'chapter' : IDL.Text,
  });
  
  return IDL.Service({
    'addTaskToSyllabusItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createSyllabusItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllSyllabusItems' : IDL.Func([], [IDL.Vec(SyllabusItem)], ['query']),
    'getSyllabusItem' : IDL.Func([IDL.Text], [SyllabusItem], ['query']),
    'updateTaskStatus' : IDL.Func([IDL.Text, IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };